# Generated by Django 4.1.7 on 2023-06-30 08:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_reusableform_name_alter_reusableform_form_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableform',
            name='form_content',
            field=wagtail.fields.StreamField([], use_json_field=True),
        ),
    ]
