site_name: Wagtail formation
repo_url: https://github.com/mwesterhof/wagtail_formation
site_author: Marco Westerhof
copyright: Copyright &copy; 2023, Marco Westerhof

theme:
    name: readthedocs

nav:
    - Home: index.md
    - Features: features.md
    - Installation: installation.md
    - Basic example: basic.md
    - Advanced examples: advanced.md
    - Recipes: recipes.md
    - Documentation to-do: todo.md
